DROP TABLE IF EXISTS  cathedra, groups, students, subject, teacher, vacation, holiday, audience, lection, lectionTime, teacher_subject, group_lection CASCADE;

CREATE TABLE IF NOT EXISTS cathedra (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    cathedra_id INTEGER,
    FOREIGN KEY (cathedra_id) REFERENCES cathedra (id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS students (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    address VARCHAR(200) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(200),
    birthday TIMESTAMP NOT NULL,
    group_id INTEGER,
    FOREIGN KEY (group_id) REFERENCES Groups (id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS teacher (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    address VARCHAR(200) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(200),
    birthday TIMESTAMP NOT NULL,
    cathedra_id INTEGER,
    FOREIGN KEY (cathedra_id) REFERENCES cathedra (id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS subject (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(512) NOT NULL
);
CREATE TABLE IF NOT EXISTS vacation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    startJob TIMESTAMP NOT NULL,
    endJob TIMESTAMP NOT NULL,
    teacher_id INTEGER, -- description deleted, error in uml
    FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS lectionTime (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_lection TIMESTAMP NOT NULL,
    end_lection TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS audience (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number INTEGER NOT NULL,
    capacity INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS holiday (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(200) NOT NULL,
    start_holiday TIMESTAMP NOT NULL,
    end_holiday TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS lection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cathedra_id INTEGER,
    teacher_id INTEGER,
    subject_id INTEGER,
    lecture_time_id INTEGER,
    audience_id INTEGER, -- date deleted, error in uml
    FOREIGN KEY (cathedra_id) REFERENCES cathedra (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subject (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (lecture_time_id) REFERENCES lectionTime (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (audience_id) REFERENCES audience (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- many-to-many
CREATE TABLE IF NOT EXISTS teacher_subject (
    teacher_id INTEGER,
    subject_id INTEGER,
    FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subject (id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS group_lection (
    group_id INTEGER,
    lection_id INTEGER,
    FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (lection_id) REFERENCES lection (id) ON UPDATE CASCADE ON DELETE CASCADE
);
